include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/build/**"
    - "**/generated/**"
    - "**/.dart_tool/**"

linter:
  rules:
    non_constant_identifier_names: false
    library_private_types_in_public_api: false
    prefer_const_constructors: false
    avoid_unnecessary_containers: false
    prefer_expression_function_bodies: false
    unnecessary_this: false
    annotate_overrides: false
    avoid_redundant_argument_values: false
    always_declare_return_types: false
