name: raj_packaging
description: "The stock and order management app for the Raj Packaging."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.3+1
  responsive_sizer: ^3.3.1
  get_storage: ^2.1.1
  go_router: ^14.1.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  dropdown_search: ^5.0.6
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  syncfusion_flutter_core: ^25.2.5
  syncfusion_flutter_pdfviewer: ^25.2.5
  whatsapp_share: ^2.0.2
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_intl:
  enabled: true