name: raj_packaging
description: "The stock and order management app for the Raj Packaging."
publish_to: 'none'

version: 1.1.14+26

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management Libs
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking, Router & Storage Libs
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  go_router: ^15.2.4
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

  # Widgets Libs
  responsive_sizer: ^3.3.1
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.1
  carousel_slider: ^5.1.1
  flutter_staggered_animations: ^1.1.1
  collection: ^1.19.1
  easy_stepper: ^0.8.5+1
  flutter_native_splash: ^2.4.6
  top_snackbar_flutter: ^3.3.0

  # File Libs
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  package_info_plus: ^8.3.0

  # Syncfusion Libs
  syncfusion_flutter_core: ^30.1.37
  syncfusion_flutter_pdfviewer: ^30.1.37
  syncfusion_flutter_charts: ^30.1.37

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#FDC674"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#FDC674"